// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khrpfsdzfklffylmgsan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtocnBmc2R6ZmtsZmZ5bG1nc2FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTg5ODUsImV4cCI6MjA2MzM5NDk4NX0.kTPJVnJklKWjWGjDMhcTkBWGFUvM0wkosxAFqEUED08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);